### ISSUE TITLE
NoComponentId error when open a migrated page form classic to modern using PnP PowerShell

### ISSUE THREAD

**Issue by mohammadamer** [pnp/pnpframework#188]
#### Reporting an Issue or Missing Feature
- [x] Page Transformation: Page is not looking correct after transformation.

#### Overview
A sub site migrated to be a new Communication site and It has some Classic Pages (WebPart and Wiki Pages)

#### Expected or Desired Behavior
Excepted behavior is to have classic pages converted to modern pages.
Excepted to see logs on SharePoint or file system by using the parameters (-LogType) (-LogFolder) but no reports generated

#### Observed Behavior
Observed that migrated pages created in only specific Page library regardless of where the source page is existing despite it should be created in the SitePages Libraries.
All converted pages are giving error "NoComponentId" when trying to open any one.

`Sorry, something went wrong`
`NoComponentId`
`TECHNICAL DETAILS`
`Troubleshoot issues with Microsoft SharePoint Foundation.`
`Correlation ID: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx`

#### Observed Errors in power Shell for some pages
ConvertTo-PnPPage : Page is an basic aspx page...can't currently transform that one, sorry!
ConvertTo-PnPPage : Page 'xxxxx.aspx' does not exist

#### PnpPowerShell Script
[link to the PowerShell](https://github.com/pnp/sp-dev-modernization/blob/master/Scripts/PageTransformation/Convert-WikiAndWebPartPages.ps1)

#### PnpPowerShell versions:
- [x] PnP.PowerShell 1.3.0

#### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by jansenbe** [comment]
@mohammadamer : please share a transformation log

Are you transforming pages living in library different from "Site Pages"? All modern pages must live in the Site Pages library, if the source page lives in another library we're adding the generated modern page in a folder named like the source library.

**Comment by mohammadamer** [comment]
Hi @jansenbe 

I'm transforming pages that are not living in Sites Pages library.
I observed the following:
Page transformed but not in Site Pages library, it is transformed to another library.
No logs generated either with -LogType is File or -LogType is SharePoint

When open the migrated page it raises the following error:
Sorry, something went wrong
NoComponentId
TECHNICAL DETAILS
Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx

**Comment by jansenbe** [comment]
Please share the command line you're using, all modern pages **must** live in the SitePages library, no exception...so if the modern page get's created elsewhere that's really weird. Please share the name of the source library, we've an open issue when a there's for example a wiki page library named aaaa and a sitepages library...since the code checks for the sitepages library based upon type it finds the aaaa library first...

**Comment by mohammadamer** [comment]
Source Library Name: OmHK
Pages Transformed to Library called: Kistakontoret
SitePages library has no files migrated to it.

Power Shell Script : [link](https://github.com/pnp/sp-dev-modernization/blob/master/Scripts/PageTransformation/Convert-WikiAndWebPartPages.ps1)

**Comment by jansenbe** [comment]
@mohammadamer : I just fixed the site page library detection code, this should fix this problem as well. Please try again with the next nightly and report back

**Comment by jansenbe** [comment]
There was also a bug with spaces in the file name of the page...causing the nocomponentid error. That has been fixed as well and will appear in the next nightly

**Comment by jansenbe** [comment]
@mohammadamer : closing as this should be fixed. If not fixed cross check you're using the latest version and provide the error info

**Comment by mohammadamer** [comment]
Hi! @jansenbe 

unfortunately, I still have the same issue.

What I have done is
Uninstall and Install PnP.PowerShell
Run the cmdlet 
Page migrated to another library not SitePages
Logs was not generated - I used (-LogType File)

I tried to convert a page living in a library called "OmHK" and a page living in a library called "Huvudkontoret" and a page living in a library called "SitePages". Probably there is something wrong with the SharePoint Site since it's a migrated site collection from a sub-site.

When I open the page it gives me the below error
_Sorry, something went wrong
NoComponentId
TECHNICAL DETAILS
Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx_

**Comment by jansenbe** [comment]
Please try tomorrow, the last fix was not yet in the current nightly

**Comment by mohammadamer** [comment]
Issue resolved with the latest nightly build
Awesome! classic pages that are living in different libraries converted to modern in SitePages library.
Great! Thanks @jansenbe

**Comment by LogicElite** [comment]
> @mohammadamer : I just fixed the site page library detection code, this should fix this problem as well. Please try again with the next nightly and report back

Amazing work! Much appreciated. Our pages are now converting with success.
