### ISSUE TITLE
Invoke-PnPTemplates fails provisioning new site pages

### ISSUE THREAD

**Issue by ohaak2** [pnp/pnpframework#572]
Provisioning new client side pages using a PnP template fails with error 'One of the identified items was in an invalid format'.

Error is reproduceable by the following steps:

1. Create a new plain-vanila page in a SharePoint site.
2. Export the page as PnP template using Export-PnPPage.
3. Delete the page in the site.
4. Try recreating the page by applying the previously exported PnP tempalte using Invoke-PnPTemplate. This will produce the error 'One of the identified items was in an invalid format'. The page nevertheless has been created, but somehow is incomplete / non functional. 
5. Re-applying the template by calling Invoke-PnPTemplate again won't change a thing.

Interestingly the template will be applied without issues, if the page already exists in the site. So currently it's a kind of work around for me to first create the page using SharePoint GUI and then applying the template.

Please note: We don't have that issue in all tenants, but we can now reproduce it at least in two of them.

**Comment by ohaak2** [comment]
Some additonal information:

As mentioned above the page will nevertheless being created (kind of). Accessing the page from SitePages libray will get an error page like this (sorry it's in German, but I think you'll get the gist of it):

<img width="699" alt="image" src="https://user-images.githubusercontent.com/91688676/149190528-522aa201-b5be-4bd2-b50d-9e3d68882526.png">

**Comment by ohaak2** [comment]
Issues can be isolated to the acutal page creation:

Just creating a new page like this:
```
Add-PnPPage -Name "TEST"
```

... will result in the error message: _Add-PnPPage: One of the identified items was in an invalid format._

By the way - the same is (not surprisingly) true, if one tries to remove such a broken page:

```
Remove-PnPPage -Identity 'TEST.aspx'
```
Result: _Remove-PnPPage: One of the identified items was in an invalid format._

**Comment by ohaak2** [comment]
We've now identified the reason behind our issue. It's infact nothing tenant specifc but in our case occurs just on all intranet sites using a specific content type.

Content type was referencing a site taxonomy based site field that was configured to have a specific default value. The field definition contained a default value like this:

```xml
<Default>21;#Local|2ebe66bc-885a-49df-b930-20926596de15</Default>
```
The fact that the id number '21' here might not correlate to the correct value in the taxonomy hidden list was so far never an issue for any type of provisioning, but it seems to be now - and not just for items using the content type in question, but in fact for all items (site pages) created in the library (no matter which content type). Funny thing here is, that creating a new page using the same content type using SharePoint GUI has no issues.

Our fix is now changing the field definition like this:

```xml
<Default>-1;#Local|2ebe66bc-885a-49df-b930-20926596de15</Default>
```

Thanks to PnP PowerShell it's quite easy to fix all sites involved using something like this:

```powershell
Set-PnPField -Identity 'Scope' -Values @{DefaultValue = '-1;#Local|2ebe66bc-885a-49df-b930-20926596de15'
```

**Comment by jansenbe** [comment]
@ohaak2 : scanning over this, seems your issue is resolved and it can be closed?

**Comment by conncampbell** [comment]
This is not resolved as the issue effects the template system too.

**Comment by SaltySweats** [comment]
This is still an issue. Thank you @ohaak2  for the workaround. Replacing all default values in our pnp templates using -1 fixed the issue: 
![image](https://github.com/pnp/pnpframework/assets/36278490/675cfea3-37bf-4075-a56b-1dcc327cb100)

Calling Add-PnPPage or Invoke-PnPSiteTemplate for new pages work without issue.
